//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Contact page</summary>
	[PublishedContentModel("contactPage")]
	public partial class ContactPage : DocumentBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// Button Text
		///</summary>
		[ImplementPropertyType("buttonText")]
		public string ButtonText
		{
			get { return this.GetPropertyValue<string>("buttonText"); }
		}

		///<summary>
		/// ContactTitle
		///</summary>
		[ImplementPropertyType("contactTitle")]
		public string ContactTitle
		{
			get { return this.GetPropertyValue<string>("contactTitle"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// email title
		///</summary>
		[ImplementPropertyType("emailTitle")]
		public string EmailTitle
		{
			get { return this.GetPropertyValue<string>("emailTitle"); }
		}

		///<summary>
		/// Phone1
		///</summary>
		[ImplementPropertyType("phone1")]
		public string Phone1
		{
			get { return this.GetPropertyValue<string>("phone1"); }
		}

		///<summary>
		/// Phone2
		///</summary>
		[ImplementPropertyType("phone2")]
		public string Phone2
		{
			get { return this.GetPropertyValue<string>("phone2"); }
		}

		///<summary>
		/// placeholder - email
		///</summary>
		[ImplementPropertyType("placeholderEmail")]
		public string PlaceholderEmail
		{
			get { return this.GetPropertyValue<string>("placeholderEmail"); }
		}

		///<summary>
		/// placeholder - message
		///</summary>
		[ImplementPropertyType("placeholderMessage")]
		public string PlaceholderMessage
		{
			get { return this.GetPropertyValue<string>("placeholderMessage"); }
		}

		///<summary>
		/// placeholder - name
		///</summary>
		[ImplementPropertyType("placeholderName")]
		public string PlaceholderName
		{
			get { return this.GetPropertyValue<string>("placeholderName"); }
		}

		///<summary>
		/// placeholder - phone
		///</summary>
		[ImplementPropertyType("placeholderPhone")]
		public string PlaceholderPhone
		{
			get { return this.GetPropertyValue<string>("placeholderPhone"); }
		}

		///<summary>
		/// VisitOurs
		///</summary>
		[ImplementPropertyType("visitOurs")]
		public string VisitOurs
		{
			get { return this.GetPropertyValue<string>("visitOurs"); }
		}
	}
}
