//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home page</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : DocumentBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner 1 Header
		///</summary>
		[ImplementPropertyType("banner1Header")]
		public string Banner1Header
		{
			get { return this.GetPropertyValue<string>("banner1Header"); }
		}

		///<summary>
		/// Banner 1 Image
		///</summary>
		[ImplementPropertyType("banner1Image")]
		public string Banner1Image
		{
			get { return this.GetPropertyValue<string>("banner1Image"); }
		}

		///<summary>
		/// Banner 2 Header
		///</summary>
		[ImplementPropertyType("banner2Header")]
		public string Banner2Header
		{
			get { return this.GetPropertyValue<string>("banner2Header"); }
		}

		///<summary>
		/// Banner 2 Image
		///</summary>
		[ImplementPropertyType("banner2Image")]
		public string Banner2Image
		{
			get { return this.GetPropertyValue<string>("banner2Image"); }
		}

		///<summary>
		/// Banner 3 Header
		///</summary>
		[ImplementPropertyType("banner3Header")]
		public string Banner3Header
		{
			get { return this.GetPropertyValue<string>("banner3Header"); }
		}

		///<summary>
		/// Banner 3 Image
		///</summary>
		[ImplementPropertyType("banner3Image")]
		public string Banner3Image
		{
			get { return this.GetPropertyValue<string>("banner3Image"); }
		}
	}
}
