//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Project</summary>
	[PublishedContentModel("projectPage")]
	public partial class ProjectPage : InnerPage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public string Category
		{
			get { return this.GetPropertyValue<string>("category"); }
		}

		///<summary>
		/// Date
		///</summary>
		[ImplementPropertyType("date")]
		public DateTime Date
		{
			get { return this.GetPropertyValue<DateTime>("date"); }
		}

		///<summary>
		/// dikla-richText
		///</summary>
		[ImplementPropertyType("diklaRichText")]
		public IHtmlString DiklaRichText
		{
			get { return this.GetPropertyValue<IHtmlString>("diklaRichText"); }
		}

		///<summary>
		/// GalleryImages
		///</summary>
		[ImplementPropertyType("galleryImages")]
		public string GalleryImages
		{
			get { return this.GetPropertyValue<string>("galleryImages"); }
		}

		///<summary>
		/// Image 1
		///</summary>
		[ImplementPropertyType("image1")]
		public string Image1
		{
			get { return this.GetPropertyValue<string>("image1"); }
		}

		///<summary>
		/// Image 2
		///</summary>
		[ImplementPropertyType("image2")]
		public string Image2
		{
			get { return this.GetPropertyValue<string>("image2"); }
		}

		///<summary>
		/// Investor
		///</summary>
		[ImplementPropertyType("investor")]
		public string Investor
		{
			get { return this.GetPropertyValue<string>("investor"); }
		}

		///<summary>
		/// Location
		///</summary>
		[ImplementPropertyType("location")]
		public string Location
		{
			get { return this.GetPropertyValue<string>("location"); }
		}

		///<summary>
		/// Project details content 1
		///</summary>
		[ImplementPropertyType("projectDetailsContent1")]
		public IHtmlString ProjectDetailsContent1
		{
			get { return this.GetPropertyValue<IHtmlString>("projectDetailsContent1"); }
		}

		///<summary>
		/// Project details content 2
		///</summary>
		[ImplementPropertyType("projectDetailsContent2")]
		public IHtmlString ProjectDetailsContent2
		{
			get { return this.GetPropertyValue<IHtmlString>("projectDetailsContent2"); }
		}

		///<summary>
		/// Project details header 1
		///</summary>
		[ImplementPropertyType("projectDetailsHeader1")]
		public string ProjectDetailsHeader1
		{
			get { return this.GetPropertyValue<string>("projectDetailsHeader1"); }
		}

		///<summary>
		/// Project details header 2
		///</summary>
		[ImplementPropertyType("projectDetailsHeader2")]
		public string ProjectDetailsHeader2
		{
			get { return this.GetPropertyValue<string>("projectDetailsHeader2"); }
		}

		///<summary>
		/// Value
		///</summary>
		[ImplementPropertyType("value")]
		public string Value
		{
			get { return this.GetPropertyValue<string>("value"); }
		}
	}
}
