//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Service</summary>
	[PublishedContentModel("servicePage")]
	public partial class ServicePage : InnerPage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "servicePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ServicePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ServicePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content1
		///</summary>
		[ImplementPropertyType("content1")]
		public IHtmlString Content1
		{
			get { return this.GetPropertyValue<IHtmlString>("content1"); }
		}

		///<summary>
		/// Content 2
		///</summary>
		[ImplementPropertyType("content2")]
		public IHtmlString Content2
		{
			get { return this.GetPropertyValue<IHtmlString>("content2"); }
		}

		///<summary>
		/// Description1
		///</summary>
		[ImplementPropertyType("description1")]
		public IHtmlString Description1
		{
			get { return this.GetPropertyValue<IHtmlString>("description1"); }
		}

		///<summary>
		/// Description2
		///</summary>
		[ImplementPropertyType("description2")]
		public IHtmlString Description2
		{
			get { return this.GetPropertyValue<IHtmlString>("description2"); }
		}

		///<summary>
		/// Header 1
		///</summary>
		[ImplementPropertyType("header1")]
		public IHtmlString Header1
		{
			get { return this.GetPropertyValue<IHtmlString>("header1"); }
		}

		///<summary>
		/// Header 2
		///</summary>
		[ImplementPropertyType("header2")]
		public IHtmlString Header2
		{
			get { return this.GetPropertyValue<IHtmlString>("header2"); }
		}

		///<summary>
		/// Image 1
		///</summary>
		[ImplementPropertyType("image1")]
		public string Image1
		{
			get { return this.GetPropertyValue<string>("image1"); }
		}

		///<summary>
		/// Image 2
		///</summary>
		[ImplementPropertyType("image2")]
		public string Image2
		{
			get { return this.GetPropertyValue<string>("image2"); }
		}
	}
}
